### ISSUE TITLE
Middleware's request.ip doesn't provide the client's IP

### ISSUE THREAD

**Issue by FearlessSlug** [opennextjs/opennextjs-aws#163]
In Vercel hosted NextJS app in middleware.ts you can get the client's IP from `request.ip` (might also be in route.ts file in the app directory but I'm not sure and haven't tested there), but in SST deployed NextJS app there's nothing in the `request.ip`.

**Comment by masterbater** [comment]
request.remoteAddress

**Comment by daveycodez** [comment]
Both of these no longer exist on NextRequest

**Comment by sommeeeer** [comment]
We can probably close this. Today you would get the IP address from the request headers. either `cloudfront-viewer-address` or `x-forwarded-for`

**Comment by conico974** [comment]
As @sommeeeer pointed out there is other ways to get the IP address.

**Comment by YHADJRABIA** [comment]
Here is the new way to do it with Nextjs 15: using [ipAddress](https://vercel.com/docs/functions/functions-api-reference/vercel-functions-package#ipaddress)
