### ISSUE TITLE
Redirect loop with trailing slashes appended to end of query string

### ISSUE THREAD

**Issue by leanderiversen** [opennextjs/opennextjs-aws#283]
Hi,

I have encountered an issue that causes a redirect loop, and can confirm that it works as expected locally.

Given the following URL, `https://www.example.com/example?query=example`, I would expect it to redirect to `https://www.example.com/example/?query=example` when `trailingSlash` is enabled in `next.config.js`.

However, a redirect loop occurs, and trailing slashes gets appended to the end of the query string, like this: `https://www.example.com/example?query=example////////////////////////////////////`.

**Versions**
Next: 13.4.17 (app directory)
SST: 2.29.2
OpenNext: 2.2.3

Happy to provide more details if needed.

Thank you!

**Comment by khuezy** [comment]
Should be fixed in the upcoming 2.2.4

**Comment by leanderiversen** [comment]
@khuezy Great, thank you very much!

**Comment by khuezy** [comment]
@leanderiversen can you try 2.2.4 to see if it's fixed.

**Comment by khuezy** [comment]
you can override the `buildCommand` on NextjsSite, `npx open-next@2.2.4 build`

**Comment by leanderiversen** [comment]
@khuezy I can confirm that the issue has been fixed. Thank you!

**Comment by khuezy** [comment]
Fixed in 2.2.4
