### ISSUE TITLE
Cloudflare deployment

### ISSUE THREAD

**Issue by Meemaw** [opennextjs/opennextjs-aws#294]
Wondering if there is any plan in supporting other edge providers, e.g Cloudflare?

**Comment by khuezy** [comment]
You can join our discussion here: https://discord.com/channels/983865673656705025/1164872233223729152

I think Fly.io is a great choice, and adding Cloudflare to that would be 🔥

**Comment by conico974** [comment]
There is some basic support for Cloudflare Workers in [OpenNext V3](https://github.com/sst/open-next/releases/tag/v3.0.0).
Right now the middleware and app router api route can work in Cloudflare workers. (Even if no IAC tool support this right at the moment )

**Comment by conico974** [comment]
For full support : https://github.com/opennextjs/opennextjs-cloudflare
