### ISSUE TITLE
MicroApps and OpenNext - Can we work together?

### ISSUE THREAD

**Issue by huntharo** [opennextjs/opennextjs-aws#324]
Hello - I'm the developer of "MicroApps" which allows multiple Next.js apps (and other frameworks or static-only apps) to deploy to a single host on CloudFront and using an OriginRequest handler and DynamoDB for routing specific users to specific versions of an app.  The system allows requests to remain isolated across versions where the browser will send all `_next/data` requests and static file requests to the exact corresponding server-side version (apparently Vercel now has something similar to this called "version preview" or some such).  Multiple versions of an app can be accessed at a time, allowing for fast evaluation of when a bug was introduced in Production.

https://github.com/pwrdrvr/microapps-core/

I'd love to consolidate these projects and work together!  Is anyone available to do a Google Meet or other type of meeting to see what we can do?

To summarize some of the unique features of MicroApps:
- In use at "a big company" that I'm aware of for both internal apps and customer-facing functionality
- Multiple framework support capability (primarily Next.js and static apps at the moment, but others just need example apps that add the versions to the path)
- Multiple versions at once
- Magic sauce to allow server-side webpack bundling of the Lambda functions (reducing the file count by thousands, Lambda size by hundreds of MB, and cutting the cold start time of the Lambdas by more than 50%): https://github.com/pwrdrvr/microapps-app-nextjs-demo/blob/main/patches/next%2B13.3.1.patch
- Release console for controlling default versions for users doing a hard load of a page: https://github.com/pwrdrvr/microapps-app-release
  - Live public version: https://apps.ghpublic.pwrdrvr.com/release 
  - Direct access to latest version if default is changed: https://apps.ghpublic.pwrdrvr.com/release?appver=0.5.3
  - Direct access to an older version: https://apps.ghpublic.pwrdrvr.com/release?appver=0.4.7
  - If you change the default version and reload the page you will see that all the static and `_next/data` and `api` paths change to that corresponding version

Let me know if you'd like to collaborate / consolidate, thanks - Harold

**Comment by khuezy** [comment]
Hi Harold that sounds great! It's Thanksgiving weekend in the US so there might not be any activity here til next week.
CC: @fwang @conico974 

Have you joined our [discord](https://discord.com/channels/983865673656705025/1164872233223729152)? There's a V3 thread and your feature sets sound great to have in general.

**Comment by conico974** [comment]
That's pretty cool.
The easiest would be to create a thread on the open next channel on discord.

I've took a really quick look at your repo, and I think it should doable to integrate with open-next.
If I understood correctly, you could just replace the current server lambda that uses LWA with the architecture of open next.
https://open-next.js.org/advanced/architecture. 
All the tags and cache files are prefixed with next `BUILD_ID` so it should work fine in your case

**Comment by huntharo** [comment]
Cool, thanks for the replies already!  Yup, I'm in the US.  I'll get into the discord as suggested.  Is anyone going to re:Invent next week?  I will be there if anyone wants to meet up.

**Comment by khuezy** [comment]
I'm actually banned from all Amazon related facilities. Have fun there though and send us their secrets.
