### ISSUE TITLE
Preview mode does not work for Next 12 from open-next 2.2.0 onwards

### ISSUE THREAD

**Issue by breningham** [opennextjs/opennextjs-aws#339]
As discussed in Discord https://discord.com/channels/983865673656705025/1186653005945245746 

TL;DR: as of open-next 2.2.0 Next 12's preview mode does not work, when accessing a route that sets the  preview mode cookies (e.g `/api/set-preview?slug=redirect-me-to-here`), the initial preview mode cookies are set, but when navigating to the resulting page, it 404's and preview cookies are unset. 

open-next 2.1.5 works as expected.

**Comment by 54nd10** [comment]
Having the same issue with Next 14 just no 404 any updates?

**Comment by conico974** [comment]
It does work for me in V3 with next 14. ( Not tested yet in next 12)

**Comment by conico974** [comment]
It should be fixed now, if that's still an issue just reopen this
