### ISSUE TITLE
next/image `url` param is incorrect when using `basePath`

### ISSUE THREAD

**Issue by khalil-omer** [opennextjs/opennextjs-aws#388]
Using 3.0.0-rc.8, with 'app' as the `basePath`, this URL is attempted to be fetched but fails:

`/app/_next/image?url=%2Fsplash-screen-icon.png&w=96&q=75`

This is the correct URL that should be fetched, which works:

`/app/_next/image?url=%2Fapp%2Fsplash-screen-icon.png&w=96&q=75`

This was discussed in https://github.com/sst/sst/issues/4935 however I believe the fix would be in OpenNext, not SST. If I'm incorrect I'll reopen that issue.

**Comment by conico974** [comment]
Looks like this is the intended behaviour
https://nextjs.org/docs/app/api-reference/next-config-js/basePath#images
