### ISSUE TITLE
Next Cache never expires with Pages Router

### ISSUE THREAD

**Issue by SapientMatt** [opennextjs/opennextjs-aws#389]
Hi,

I'm currently attempting to use ISR, without on demand invalidation, where my pages are supposed to expire after 10 minutes.
I can see the cloudfront cache expire and it coming to next, however next never seems to regenerate the page no matter how long I wait.
Deleting all files with the _cache/ prefix in the app bucket seems to force this regeneration to occur.

Additionally, there never seem to be any entries added to the dynmaodb table.

On next 13.5.6 and opennext 2.3.5

**Comment by conico974** [comment]
App router or Page router ? Page router don't use dynamodb
How are you deploying ? With sst ?
What are the `X-Nextjs-Cache`, `Cache-Control` and `X-Cache` headers for your stale pages ? 
You're not building on windows ?

**Comment by SapientMatt** [comment]
Yeah deploying via SST.

x-nextjs-cache: STALE
Cache-Control: s-maxage=2, stale-while-revalidate=2592000
X-Cache: RefreshHit from cloudfront
Age: 92

Have deployed from local built on windows and from pipeline built on ubuntu, both behave similarly.
________________________________

**Comment by conico974** [comment]
Try adding `x-prerender-revalidate` to the list of allowed cache policy headers in cloudfront. 
There is a PR for that already https://github.com/sst/sst/pull/3713
You can do it in the aws console for testing.

FYI open-next doesn't work on windows https://github.com/sst/open-next/issues/385

If this doesn't solve the issue, you'll need to create a minimum repro

**Comment by fwang** [comment]
just chiming in. PR is merged. `2.41.3` should have `x-prerender-revalidate` included in the allowed headers.

**Comment by conico974** [comment]
I'm going to close this old issue.
If that's still an issue, reopen and provide a reproduction
