### ISSUE TITLE
[Feature Request] - package agnostic runner

### ISSUE THREAD

**Issue by tommyboylab** [opennextjs/opennextjs-aws#479]
I've recently tried moving from serverless to SST ION and noticed that it requires yarn as the default package manager based on the OpenNext deployment.

Trying to run the application with another package manager throws errors such as missing the package manager, or

`Error: Next.js requires react >= 18.2.0 to be installed.`

I would like to be able to execute the deployment and dev environments using the package manager of my choice (in this case Bun)

Thank you.

**Comment by conico974** [comment]
OpenNext does support the 4 package manager (i.e. npm, pnpm, yarn and bun).
The error you show has nothing to do with OpenNext, `Error: Next.js requires react >= 18.2.0 to be installed` is thrown by Next not OpenNext
