### ISSUE TITLE
Is PPR supported?

### ISSUE THREAD

**Issue by wottpal** [opennextjs/opennextjs-aws#527]
PPR is highlighted in the [OpenNext Cloudflare Docs](https://opennext.js.org/cloudflare#not-yet-supported-nextjs-features) (as not supported). [OpenNext AWS Docs](https://opennext.js.org/aws) don't specifically mention it (it probably should), so I was wondering whether it's supported (in it's current experimental state) and if the goal is 100% feature parity in general.

**Comment by conico974** [comment]
It is not supported at the moment but will be in the future (probably when it will be stable, or at least more stable)

There is 2 kind of PPR, the one in next standalone and the one in vercel.

PPR as it is in next standalone would not work very well in the current setup and could even be slower than a normal SSR page. If rendering the prerendered part is faster than fetching the cache on S3 it's not worth it. 

The one in vercel is different and requires a bit more work, but most of the necessary pieces are already there

**Comment by khuezy** [comment]
According to the Vercel devs, enabling `ppr` without the complete infrastructure still has some benefits... so turn it on and see if it's better or worse.

**Comment by conico974** [comment]
It doesn't work right now, we need to change a few things for it to work even with standalone

**Comment by conico974** [comment]
There is now basic support for it in #542
