### ISSUE TITLE
/robots.txt and /sitemap.xml should be static (like favicon.ico)

### ISSUE THREAD

**Issue by Chenalejandro** [opennextjs/opennextjs-aws#533]
Currently the robots.txt and sitemap.xml are not static. We should make it behave like favicon.ico.

**Comment by sommeeeer** [comment]
> Currently the robots.txt and sitemap.xml are not static. We should make it behave like favicon.ico.

i tested this with a barebones fresh next.js project containing a static `sitemap.xml` and `robots.txt`.

deployed to vercel i get these headers:
```bash
# robots.txt
curl -I https://opennext-robots-sitemap-static.vercel.app/robots.txt | grep -i cache
cache-control: public, max-age=0, must-revalidate
x-vercel-cache: HIT

# sitemap.xml
curl -I https://opennext-robots-sitemap-static.vercel.app/sitemap.xml | grep -i cache
cache-control: public, immutable, no-transform, max-age=31536000
x-vercel-cache: HIT
```

deployed to aws with opennext and sstv3:
```bash
# robots.txt
curl -I https://d94es8et6eeml.cloudfront.net/robots.txt | grep -i cache
x-nextjs-cache: HIT
cache-control: public, max-age=0, must-revalidate
x-cache: Miss from cloudfront

# sitemap.xml
curl -I https://d94es8et6eeml.cloudfront.net/sitemap.xml | grep -i cache
x-nextjs-cache: HIT
cache-control: public, immutable, no-transform, max-age=31536000
x-cache: Hit from cloudfront
```

for me they look almost the same, if you want to cache on cloudfront you can set the `cache-control` header to whatever you want in the middleware.

**Comment by Chenalejandro** [comment]
I'm getting ~200ms when accessing https://d94es8et6eeml.cloudfront.net/robots.txt because I live far from the origin. It should be behaving like  https://opennext-robots-sitemap-static.vercel.app/robots.txt, where the response time is less than 50ms worldwide. Are there any reason that not being the default behavior?

**Comment by sommeeeer** [comment]
> Are there any reason that not being the default behavior?

yeah thats becaues its not cached in cloudfront right now. if you look at the `x-cache` header its saying `Miss from cloudfront` 

if i want it to be cached on cloudfront i have to change the `cache-control` header for `robots.txt` in my `middleware.ts`. that way cloudfront will cache it properly.

**Comment by Chenalejandro** [comment]
Understood! I was using vercel to host my website and I had the static assets (favicon.ico, robots.txt and sitemap.xml) blacklisted in the middleware config matcher since vercel already managed that for me.
Thanks for the reply!
