### ISSUE TITLE
Associate WAF ACL

### ISSUE THREAD

**Issue by luisiturrios1** [opennextjs/opennextjs-aws#534]
I'm currently using the OpenNext AWS setup for my project, and I'd like to add an AWS WAF ACL to my CloudFront distribution to enhance security. However, I couldn't find any documentation or clear guidance on how to associate an existing WAF ACL with the CloudFront distribution in the current OpenNext setup.

**Comment by sommeeeer** [comment]
this is more of a SST question than an open-next.

if you are using sstv2 you need to create in using `aws-cdk-lib`  then pass the `id` through to `cdk.distributionwebAclId` on the `NextjsSite` construct.

if you are using ion you need to use `aws.wafv2.WebAcl`, and then use `transform` on `sst.aws.Nextjs`.

**Comment by luisiturrios1** [comment]
Thanks a lot for your response, this works for me 

```
new sst.aws.Nextjs("MyApp", {
  transform: {
    cdn: {
      transform: {
        distribution: {
          webAclId: "arn:aws:wafv2:us-east-1:XXXXXXXXXXXX.....",
        },
      },
    },
  },
});
```
