### ISSUE TITLE
@opentelemetry/api does not seem to work with Next.js 15

### ISSUE THREAD

**Issue by ruchernchong** [opennextjs/opennextjs-aws#587]
Error: 
```bash
Could not resolve "@opentelemetry/api"

    node_modules/.pnpm/next@15.0.0_@babel+core@7.25.8_react-dom@19.0.0-rc-69d4b800-20241021_react@19.0.0-rc-69d4b800_uh4t4uztsorvxmrfdwbfot353m/node_modules/next/dist/server/lib/trace/tracer.js:46:18:
      46 │     api = require('@opentelemetry/api');
         ╵                   ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@opentelemetry/api" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
```

[Here](https://github.com/sgcarstrends/web/actions/runs/11463504649/job/31897558787) is the reference for the error mentioned.

---

Of course, I can temporary fix it by using the suggested solution, but would be nice if this will also be gracefully fixed by the next release.

**Comment by conico974** [comment]
This has been fixed in 3.1.3, upgrade to at least this version.
If that's still an issue just reopen the issue

**Comment by Gr33nLight** [comment]
Hello @conico974 I have this issue, I'm using sst@2.43.7 do I have to migrate to sst ion v3 or is there a workaround for v2 ? 
Thanks in advance.

**Comment by conico974** [comment]
@Gr33nLight Update sst to `2.47` by default it uses OpenNext 3.2.2
If you want to use the latest OpenNext version just set it in https://v2.sst.dev/constructs/NextjsSite#opennextversion. FYI latest is 3.4.1

**Comment by Gr33nLight** [comment]
> [@Gr33nLight](https://github.com/Gr33nLight) Update sst to `2.47` by default it uses OpenNext 3.2.2 If you want to use the latest OpenNext version just set it in https://v2.sst.dev/constructs/NextjsSite#opennextversion. FYI latest is 3.4.1

Thanks for the quick response, much appreciated.
