### ISSUE TITLE
Data routes without base path return 404 

### ISSUE THREAD

**Issue by alebelcor** [opennextjs/opennextjs-aws#670]
Hi,

I'm seeing an error where data routes aren't being handled correctly and end up as HTTP 404.

These are the versions I'm using:

* `next` version: `14.2.20`
* `@opennextjs/aws` version: `3.2.2`

Adding log statements to the package I was able to figure out the 404s was coming from [here](https://github.com/opennextjs/opennextjs-aws/blob/v3.2.2/packages/open-next/src/core/routingHandler.ts#L198-L207), i.e. the data routes aren't being detected as anything.

Not 100% sure but it sort of looks like the code _should_ be going into [this block](https://github.com/opennextjs/opennextjs-aws/blob/v3.2.2/packages/open-next/src/core/routing/matcher.ts#L353-L365) but isn't for me.

I'm using a `basePath` (in my `next.config.js`) for my app, so to illustrate let's say it's `/foo`.

I noticed `dataPattern` didn't include the base path/prefix so I thought might as well try and hardcode it [here](https://github.com/opennextjs/opennextjs-aws/blob/v3.2.2/packages/open-next/src/core/routing/matcher.ts#L339) to test, e.g.:

```ts
const dataPattern = `/foo/_next/data/${buildId}`;
```

And it worked. The data routes started to work (i.e. no 404) after that.

Is it possible the base path/prefix is missing on that line and should be added? Or maybe it's something else that's odd in my setup that could be causing OpenNext to not work for data routes?

I'd appreciate any feedback.

Thanks!

**Comment by conico974** [comment]
You're right it should be done there.
Something like that should do the trick `${NextConfig.basePath ?? ""}/_next/data/${buildId}` (Not tested).
Could you open a PR for it ?

**Comment by alebelcor** [comment]
Absolutely, I'll have something soon.

Thank you for confirming.

**Comment by alebelcor** [comment]
Fixed in https://github.com/opennextjs/opennextjs-aws/pull/672

Thanks for the help!

Closing this.
